### ISSUE TITLE
lost access to scalar 2 install

### ISSUE THREAD

**Issue by rcrath** [anvc/scalar#102]
Hi, 

I have lost access to my scalar login and all pages are giving 404 errors.  I am not sure, but I think a former employee tried to do something via msysql directly as there are backups of the database (see image).  

THe only pages I can get are 404, login, create new account (which does not work because of outdated recaptcha at the moment, and the landing page, which has no public info on it and lists no books.

The data is in the database, but scalar is not connecting to it.

I had a security scare a while ago and had to change the mysql password for the scalar account, but I am pretty sure it worked after that.

When I try to log in, it says my email is not in the database, but when I look in the users table it is there.

I can login to mysql from the command line using the scalar mysql user and pass that is in system/application/config/database.php

I tried updating to 2.1.11, but results were the same.

Any ideas?  My guess is it is something to do with linking the software to the database but I am not sure how to proceed.

here is a screenshot showing the database tables

if this is better to do by email I am fine with that, as I don't think this is a code problem.  mine is rrath [at] hawaii [dot] edu

Thanks!

![screenshot from 2018-11-09 21-31-04](https://user-images.githubusercontent.com/944636/48299000-acb4da80-e46a-11e8-8053-b4ba7bc74c96.png)

**Comment by rcrath** [comment]
fixed the recaptcha (update to 2), but registering a new user fails with "Invalid user ID or password"

**Comment by craigdietrich** [comment]
Eep!

Seems to me that the tables in the database have been emptied, ie, there’s nothing in the scalar_db_books or scalar_db_users tables, etc. This would explain the 404s and the lost logins. Can you check?

Hopefully one of those other, copied databases have all the data in them, you could swap it in.

**Comment by craigdietrich** [comment]
You might also want to check system/application/config/database.php to confirm what actual database Scalar is pointing to.

**Comment by rcrath** [comment]
OK, thanks Craig.  The pointer in database.php was incorrect.  something weird happened.  Something got renamed, either the database or the pointer in database.php.  I have the only account with access to the server as a linux user and access is through ssh, with no access for root.  and I'm pretty sure I did not do it.  I have not been able to find anything in the logs as far as suspicious ssh logins.  I am the only admin user in scalar...not sure how I could have done it by accident!  Anyway, it is resolved, thanks.
