### ISSUE TITLE
Broken Register/Learn More link

### ISSUE THREAD

**Issue by tinuola** [anvc/scalar#103]
Would like to get more info about how to create a Scalar project, but the link to Register / Learn More at http://scalar.usc.edu/scalar/ is broken.

**Comment by craigdietrich** [comment]
?

**Comment by craigdietrich** [comment]
Hi,

Not sure where you uncovered that URL?  Scalar's informational website is here:
[https://scalar.me](https://scalar.me)

... and the Guide here:
[http://scalar.usc.edu/works/guide2](http://scalar.usc.edu/works/guide2)

**Comment by tinuola** [comment]
@craigdietrich The URL is listed in README.md.
