### ISSUE TITLE
IIIF Integration

### ISSUE THREAD

**Issue by ColeDCrawford** [anvc/scalar#108]
IIIF seems like a natural technology to integrate with Scalar - it's predicated on reusing content, supports annotations, etc. Has anyone explored this? It would be great to be able to import manifests; mapping content might look something like this:
- Canvases -> Scalar Media files (images)
- IIIF Annotations -> Scalar Annotations
- Sequence -> Scalar Path (restricted to only image media)
- Collection -> Path of Paths

There could be some sort of flag on individual Scalar media that are IIIF compliant that would override the static image display and use Mirador or another IIIF viewer instead; Mirador 3 is very plugin based, so different pages could have different renderings (eg standalone images get more features, but if an image is embedded in a page the viewer is stripped down). When you go up a level to a sequence / path, Scalar would display the sequence in the IIIF viewer.

On the other side, it would be great to have Loris or another IIIF server to tile images uploaded directly to Scalar.

I'd welcome input on how we could think about structuring the plugin(s) necessary for this to happen, and what the ideal workflow for users would look like. The Omeka IIIF plugins work pretty well, but suffer from some weird mapping issues that make them less than intuitive.

**Comment by eloyer** [comment]
Thanks for reaching out! We looked at IIIF a while back, but an integration seems more doable now. Importing manifests is an interesting idea; I think there’d be some questions about round-tripping that would need to be answered (what are user expectations if they edit the content after it’s been imported?), but I could see starting with integrating Mirador as a viewer for manifests. 

Scalar’s media handling depends on being able to infer the media type from a URL. In the case of a URL to a manifest, if it’s just JSON we won’t have any clues to go on—we may have to ask users to append a param to the URL to help Scalar know what it’s looking at.

Integrating the viewer would end up involving additions to [mediaelement](https://github.com/anvc/scalar/blob/master/system/application/views/widgets/mediaelement/jquery.mediaelement.js) (viewer instantiation and config) and [scalarapi](https://github.com/anvc/scalar/blob/master/system/application/views/widgets/api/scalarapi.js) (defining a new media type), which isn’t too involved. We’d probably have some time to take a look at this in August, or if you’re interested in taking a stab at it yourself, let us know.
