### ISSUE TITLE
Add the whole squad

### ISSUE THREAD

**Issue by jskirby3** [anvc/scalar#112]
I'm in a multimedia digital processing course at DHSI at UVic and the whole class wants to try Scalar and get accounts to work with Scalar this afternoon (we're in Pacific Daylight Time). Sorry this is so last minute would it be possible for the whole squad to get accounts.

**Comment by eloyer** [comment]
@jskirby3 Can you drop me a line at http://erikloyer.com/index.php/contact/?

**Comment by eloyer** [comment]
@jskirby3 If you can DM us on Twitter @anvcscalar with your email we can take it from there.

**Comment by jskirby3** [comment]
You don't allow people to DM you on Twitter that you aren't following? I don't use Twitter so I tried to get my classmate to do it, I sent another email through the site you sent.

**Comment by jskirby3** [comment]
My email is jskirby@iastate.edu
