### ISSUE TITLE
Autoload error under PHP 7.2

### ISSUE THREAD

**Issue by jadestorm** [anvc/scalar#115]
Hi folk!  Recently we upgraded the bulk of our web servers from PHP 5.6 to PHP 7.2.  I accidentally upgraded the server that was running Scalar before getting a chance to test it and found that it would not run under PHP 7.2.

Now--- there is a semi similar issue discussed here: https://github.com/anvc/scalar/issues/77
However I do not believe it is the same thing.  We actually do install mcrypt.  (though it complains a lot about it being deprecated)

Before I get into more info -- the quick fix for us was to downgrade that server to PHP 7.1, which is perfectly fine for now.  We don't -need- that server to be at 7.1, just needed to get off 5.

Anyway, here is the message we are seeing:
ERROR - 2019-07-02 15:11:01 --> Severity: 8192  --> __autoload() is deprecated, use spl_autoload_register() instead /srv/apache/sites/scalar.chass.ncsu.edu/system/application/config/config.php 379

We -do- see plenty of deprecation warnings about mcrypt, but they don't seem to be causing problems.  It's also not lost on me that the pasted message is also a deprecation message rather than a full error.  However I did not see this autoload message mentioned in the other issue.

This occurs both with our production install, and our dev install.  production is pointing at commit a018c91040f9e3fdbafb1e0529473d0ae070b08b, dev is pointing at master.

Sadly, I don't have any other logs of interest to provide.  All I can tell you is that attempting to access scalar got a 500 response, and the message above.  Any idea what might be happening here?  We can set up a separate 7.2 server to get more info if need be.  For the time being, however, 7.1 is perfectly fine so this isn't a crisis.  =)

Thanks!

**Comment by burki** [comment]
I have no problem running master branch of Scalar on PHP 7.2 if I use one of the mcrypt workarounds described in https://github.com/anvc/scalar/issues/101 (either manually install the mcrypt module through pecl or by using https://github.com/phpseclib/mcrypt_compat). 

The deprecation message you mention should be fixed by https://github.com/anvc/scalar/commit/1c2187df483d59e8d8627f311c5dbae8fac373f0#diff-7511d638b47bfa4c8e1e03d6aff57044

**Comment by jadestorm** [comment]
Interesting, what version of php 7.2?

**Comment by craigdietrich** [comment]
@jadestorm Hi!

I'm pretty sure that @arthurian fixed the autoload deprecation issues in a recent pull request that we merged,

https://github.com/anvc/scalar/commit/5d81c0d74c9778328c61dc69fbd0d8064513fe51#diff-d1efac74368d2446e66826b453dbbb8eR381

It's not in a Release yet, but you could try updating your install from master (should be safe to do right now), and see if that fixes the warnings?

**Comment by burki** [comment]
@jadestorm I'm using both PHP 7.2.14 and 7.2.16

**Comment by jadestorm** [comment]
@burki Hrm we had 7.2.20 which I highly doubt is different enough from what you were running.  Might set this up on a different server to try some things out.  =)

@craigdietrich We did actually test that already -- under what we call scalardev.  (it's always running master)  However I don't know that we had logging turned on when we tested it so -- I'll check that.

Let me poke around and get back to y'all.  It's sounding more like the real problem is on my end somewhere -- just need to track it down!

**Comment by jadestorm** [comment]
Ok it's probably going to be next week before I get to dive into this more.  Bear with me, I'll be back in touch.  =)  Thanks!

**Comment by jadestorm** [comment]
Well, amusingly I immediately had a moment to test it after I commented.  It does appear that current master actually works, where version 2.5.4 does not appear to.  As such, I think we can chalk this up to "what @craigdietrich pointed out appears to fix it".  =)  Thanks all!  We'll decide if we want to hold back at PHP 7.1 until next release, or update to at a minimum that commit.  Gonna go ahead and close this!
