### ISSUE TITLE
mediaobjectview not set when any value is in dcterms:accessrights but not culturally sensitives

### ISSUE THREAD

**Issue by alexmerrill** [anvc/scalar#120]
A little while ago we noticed some of our images being served up from our contentdm IIIF API weren't appearing as expected.  After a little investigation @steve-taylor-wsu noticed that the mediaobjectview wasn't getting set for items that had any value in dcterms:accessRights.  I locally reverted the change made in [jquery.mediaelement.js](https://github.com/anvc/scalar/blob/master/system/application/views/widgets/mediaelement/jquery.mediaelement.js) in the May commit [2a4bada](https://github.com/anvc/scalar/commit/2a4bada3383732cfc218f992de695ae7d4b45f48?diff=unified)  and images are returning as expected on our  install.

Examples (if you want to see what is/was happening):  

With data in   dcterms:accessrights

[http://scalar.usc.edu/works/testing-2-1/abelson-hall](http://scalar.usc.edu/works/testing-2-1/abelson-hall)

Without data in dcterms:accessrights

[http://scalar.usc.edu/works/testing-2-1/abelson-hall-1](http://scalar.usc.edu/works/testing-2-1/abelson-hall-1)

**Comment by craigdietrich** [comment]
I need to defer to @eloyer on this.

Though, @alexmerrill, if you have any working solutions for figuring out CONTENTdm's URL structure for getting to images AND all of their other media types, omg, this would be so helpful!

**Comment by eloyer** [comment]
@alexmerrill Thanks for calling this out—should be fixed now.

**Comment by eloyer** [comment]
@alexmerrill Look for the fix to go live within the next week or so.
