### ISSUE TITLE
Excess space in importer, CTDA media issues, TIFF media issues

### ISSUE THREAD

**Issue by anvc** [anvc/scalar#13]
Submitter: Shalin Hai-Jew
Email: shalin@k-state.edu
Windows 7
Google Chrome 43.0.2357.81

I went into the data importer...for the Shoah Foundation VHA Online and found the following:  

In the data importer, when I have it open full screen, the results button at the bottom is invisible. If there could be less white space, that would be helpful… The following came up because nothing was found…but the information below is still helpful to know it’s there.  

Then, I went to the Cuban Theater Digital Archives resources and found the following:  

During the archive search and data download, the check (box) and Preview enables .jpgs to visualize but not .tifs.  So is there anything like a .tif viewer for possible downloadable images?  

Also, once the .tif images are downloaded to the project and placed on the page, they actually do not show up. The placeholders show on the edit view...but when the page itself is saved, the images do not show.  So .tif imports do not seem to work in terms of not showing on the page.

**Comment by eloyer** [comment]
Importers now show a warning message when no items are found; media handling has been updated to indicate that .tif images are no longer officially supported; CTDA image handling has been fixed so that other media formats can be imported from the archive.
