### ISSUE TITLE
Upload File for Import Media results in error

### ISSUE THREAD

**Issue by mew2232** [anvc/scalar#146]
Our Scalar installation recently developed a glitch and no longer will display the form to upload media files. (Forms for other types of media importation (ie. YouTube or Internet URL). We receive the following error message: 

A PHP Error was encountered
Severity: 8192
Message:  Array and string offset access syntax with curly braces is deprecated
Filename: amazon-s3-php-class/S3.php
Line Number: 2574

Can you advise us on how to repair this?

**Comment by eloyer** [comment]
Appears to be the same as [this issue](https://github.com/anvc/scalar/issues/145).

**Comment by craigdietrich** [comment]
Note that there appears to be another PHP 7.4-related problem:

https://github.com/anvc/scalar/issues/148

**Comment by craigdietrich** [comment]
This should be corrected with our new Release

https://github.com/anvc/scalar/releases/tag/2.5.15
