### ISSUE TITLE
PHP 7.4 Arc library preg_match issue

### ISSUE THREAD

**Issue by arthurian** [anvc/scalar#148]
When I attempt to upload media using PHP 7.4, I get the following error message: 

```
<h4>A PHP Error was encountered</h4>

<p>Severity: Warning</p>
<p>Message:  preg_match(): Compilation failed: escape sequence is invalid in character class at offset 20</p>
<p>Filename: store/ARC2_StoreLoadQueryHandler.php</p>
<p>Line Number: 329</p>
```

This error does not occur in PHP 7.2, which is what we are currently using.

**Steps to reproduce:**
1. Navigate to the **Upload Media File** page (_Files and Urls_ -> _Upload media files_).
2. Choose a file to upload (in my test, it was a small jpeg image) and click _Upload_.

**Expected behavior:**

I would expect the file to be uploaded and then redirected to the media page.

**Current behavior:**

The upload completes, but there is no redirect to the media page and there is no indication of success or failure. In the browser developer tools, the network tab shows that the `/upload` request completes successfully, but then the subsequent `/api/add` request fails with the above PHP error message.

**Other Comments:**

- I'm wondering if this has to do with [PHP 7.3 upgrading the PCRE engine to PCRE2](https://php.watch/versions/7.3/pcre2)? Since we skipped straight from PHP 7.2. to PHP 7.4, this is the first time we've encountered this particular issue. That might not be the problem, but it's the only thing that I could find that might explain why `preg_match` would be failing all of a sudden.
- Note that the specific line that is referenced in the error is: https://github.com/anvc/scalar/blob/31d2e9c7dec203842785fbec021d3144ae930e9b/system/application/arc/store/ARC2_StoreLoadQueryHandler.php#L329 

Any thoughts on how to resolve this?

**Comment by craigdietrich** [comment]
Shoot, yeah, this could be a big problem.  The ARC library is really complex, though, the good news is that their community is live and makes updates. But then it will require us to update ARC, which isn't trivial.  I'll write up a report on their Issue tab.

**Comment by craigdietrich** [comment]
Looks like the line in question is removed in the recent version(s) of ARC2, so I think 'simply' updating ARC will work.  Like said, it's not trivial, but I'll add it to my TODO list.

**Comment by craigdietrich** [comment]
This should be corrected with our new Release 

https://github.com/anvc/scalar/releases/tag/2.5.15
