### ISSUE TITLE
Google Photos media support

### ISSUE THREAD

**Issue by anvc** [anvc/scalar#15]
Submitter: Christopher Schreck
Email: cjschreck828@gmail.com
I'm having trouble adding a photo from url provided by Google Photos/Google Drive into my Scalar book. I've made the photo public and obtained a sharable url for a photo that I took myself and saved to Google Drive, and the Scalar program seems to think it has found it, but nothing appears when I save the media page. I had no problem with another file that I got off of a different website, just my own photos from Google Drive. I'm using a 2014 Macbook Air with the most recent OS X Yosemite operating system, with the most recent version of Safari as my browser.

**Comment by eloyer** [comment]
Suspect this is because Google Photos URLs don't point to actual files, and won't allow themselves to be embedded in an iframe.

**Comment by eloyer** [comment]
If you right click on the image itself, open it in a new tab, then use that URL for importing, Scalar will display the unscaled image in an iframe.
