### ISSUE TITLE
Help with configuring on Php 7.4?

### ISSUE THREAD

**Issue by Grantglass** [anvc/scalar#151]
Hello! I am trying to get this working on our university's servers, but I get these weird PHP errors where it prints out the PHP code. Please see this site for more details: http://timeline-225-dept-english.cloudapps.unc.edu

Does anyone have any insights?

**Comment by craigdietrich** [comment]
Hi,

You need to make sure that short_open_tag=On in php.ini, that will solve the problem.

Nb, Scalar is ready to go for PHP 7.4 but we haven't made a release for it yet, so you might get some PHP errors until you update to the release when it's ready.

**Comment by Grantglass** [comment]
That worked! Sorry, I see that now in the install instructions.
