### ISSUE TITLE
quoting a fragment of a page

### ISSUE THREAD

**Issue by rcrath** [anvc/scalar#154]
Hi everyone! THanks as always for scalar!

I am wondering if I can quote a fragment of another very long Scalar page.  The use case is that I have a large page full of testimony that would not be practical to split into hundreds of separate pages.  In the narrative page we are writing about that testimony, I want to quote particular passages on the narrative page, basically excerpting it from the full testimony while linking back to that fragment in the original testimony. The idea is that if people go back to the testimony in context, they might want to look at the rest of what that person said in order to check on our narrative or get more info.

If it is of any use, I added "id" anchors to each testifier and created a TOC on the top.  If I could have an note, annotation, or comment use the fragment link i.e., `<a href="http://example.com/scalar/testimony.html#smith-tues-Spet-23-2020">.` and actually pull in the text, a la Ted Nelson, that would be great, but I suppose I could get around it by using an external link with the passage anchored by it.  

I think I have a hacky way of doing it through an external link, but I was wondering if there is a more elegant solution.  I have seen something similar on media files, where a person has a transcript that follows along with the time line.  If you need me to clarify, please LMK, and I'll try the external link for now.

zThanks!

**Comment by eloyer** [comment]
@rcrath Scalar doesn't currently have a way of automatically pulling in an excerpt from another page. An alternative might be to import the testimony as a plain-text document, create annotations on the lines containing each segment, and then link the annotations as notes on the quoting page. If you're interested in this approach, it'd be worth doing a small test to see if it gives you the experience you're going for.

**Comment by rcrath** [comment]
Ok. If I get the anxious to work in #155 that will do for now. I'll just make the whole quote into a link and make sure the links don't have underline in the style

**Comment by rcrath** [comment]
Got my [Xanadu excerpt lookalike](http://udigix.net/scalar/ethnic-studies-anniversary-/community-testimony). Have to type in the quote and it goes to the full testimonial my instead of actually excerpting, but this is just what I wanted more or less and loads the huge text file quickly. Thanks for fix in #154.
