### ISSUE TITLE
Visualization changes in 2.5.13 breaking legacy publications

### ISSUE THREAD

**Issue by alexdryden** [anvc/scalar#157]
After upgrading to v2.5.15, we noticed that path visualization pages no longer look the same as they did at the time of publication. This is an example of the page as it looked at the time of publication and on version 2.5.12: 

<img width="1439" alt="Screen Shot 2021-03-10 at 6 29 23 PM" src="https://user-images.githubusercontent.com/47127862/110712126-b5e71b00-81ce-11eb-9e44-65747204eeb9.png">

And here it is after the upgrading to v2.5.15:

<img width="1439" alt="Screen Shot 2021-03-10 at 6 29 46 PM" src="https://user-images.githubusercontent.com/47127862/110712173-ca2b1800-81ce-11eb-92ab-cdefe26af649.png">

Are the changes I'm seeing the result of the visualization updates made in v2.5.13, or is there some other issue I need to identify? If they are the result of the changes in 2.5.13, are there any plans to implement some way to preserve visualizations for legacy publications?

**Comment by eloyer** [comment]
@alexdryden Thanks for reporting, this appears to be a bug. Will check back in shortly with news on the fix.

**Comment by eloyer** [comment]
@alexdryden This should be fixed now in 2.5.16.
