### ISSUE TITLE
Importing book to local install

### ISSUE THREAD

**Issue by bsteinig** [anvc/scalar#159]
Hi,

I have created a local install of scalar and would like to import an existing book from the scalar.usc.edu server onto the local install. I installed the import tool, however when importing the book url I get two messages, the first is: "Source book checks out." and the second is "The request to external RDF-JSON failed". I have checked to make sure the source book is public. I'm not sure what would be causing this error, any guidance would be appreciated.

Thank you for your help.

**Comment by craigdietrich** [comment]
Can you shoot me an email (craigdietrich at gmail) with the URL to the source book?
