### ISSUE TITLE
Page's media not showing in Gallery view

### ISSUE THREAD

**Issue by anvc** [anvc/scalar#16]
Submitter: Annie Johnson
Email: anj314@lehigh.edu
Hi,

I embedded an image on my page and set the page to Basic View. All was well. Then I changed the view to Media Gallery. When I hit save, the image did not appear on the page.

I am using Firefox 38.0.5 on a Mac (OS X).

Best,

Annie

**Comment by eloyer** [comment]
The media gallery view currently does not include the page's own media, though it's a logical expectation that it would.

**Comment by eloyer** [comment]
Now fixed.
