### ISSUE TITLE
Deprecated flag warning under PHP 7.4

### ISSUE THREAD

**Issue by paulmer** [anvc/scalar#161]
The filter_var on line 501 of system/application/controllers/books.php uses the deprecated flag FILTER_FLAG_HOST_REQUIRED which generates a visible warning when running in development mode.  This flag has been implied with FILTER_VALIDATE_URL since PHP 5.2.1 and can safely be removed from the code to eliminate the warning.

**Comment by craigdietrich** [comment]
Hi @paulmer!

So, you're saying we could replace this:

`filter_var($this->data['prev'],FILTER_VALIDATE_URL,FILTER_FLAG_HOST_REQUIRED)`

... with this:

`filter_var($this->data['prev'],FILTER_VALIDATE_URL)`

**Comment by paulmer** [comment]
That's right, more specifically the line should read:   

`
if ((filter_var($this->data['prev'],FILTER_VALIDATE_URL) === FALSE) || (filter_var($this->data['link'],FILTER_VALIDATE_URL) === FALSE)) {
`
since filter_var appears twice with that flag.  Sorry I'm not able to put a pull request together on this right now.

**Comment by craigdietrich** [comment]
Done!

https://github.com/anvc/scalar/commit/af5012503bebef991647a87587cf8c906775a4a3

Thanks!
