### ISSUE TITLE
Content disappearing in edit stages

### ISSUE THREAD

**Issue by perrymcclurecollins** [anvc/scalar#164]
I'm in the final stages of editing a book and have started moving pages to "edit review" for the author. I assigned myself as an author to test out this stage, and when I try to edit the content flashes for a moment before everything goes blank and grayed out. This doesn't seem to be an issue for the draft or edit stages, but is for edit review and clean. The content still appears on the reader end. Is there something I'm missing?

![image](https://user-images.githubusercontent.com/5411837/114624243-6937a980-9c7e-11eb-8fd9-d0fa0cac572d.png)

**Comment by eloyer** [comment]
Can you DM us a link to the book in question to [anvcscalar](https://twitter.com/anvcscalar) on Twitter?

**Comment by perrymcclurecollins** [comment]
Can you follow me back so I can DM? [perrycollins](https://twitter.com/perrycollins)

**Comment by eloyer** [comment]
Fixed in v2.5.17.
