### ISSUE TITLE
required variables at local_settings.php?

### ISSUE THREAD

**Issue by maxgray20** [anvc/scalar#170]
Hello:

My name is Maxwell Gray and I’m a digital scholarship librarian in Raynor Memorial Libraries at Marquette University. I’m seeking to run my own installation of Scalar using Bluehost for web hosting following the installation instructions. I’m able to follow the instructions, but the “log in” and “register” links don’t work at my install here: https://maxgray20.com/xcalar/. I didn’t set the reCAPTCHA, registration key and email/smtp variables at the local_settings.php file. Are any of these variables required to successfully run the install? Thank you!

Cheers,
Max

**Comment by craigdietrich** [comment]
Hi @maxgray20,

It appears that URL routing isn't working on your install.  URL routing is governed by a .htaccess file in the Scalar root folder.  I would look to see if it's there (maybe it didn't get copied? -- depending on how you're viewing your filesystem, it might be hidden).  

Also, Apache's mod_rewrite needs to be turned on for .htaccess files to operate. I'm not sure why mod_rewrite wouldn't be turned on, on a commercial server like Bluehost. I do know that on some commercial servers, "Fast CGI" needs to be turned off in order for .htaccess to work properly.

**Comment by maxgray20** [comment]
Hi @craigdietrich,

Thanks for this note! I confirmed the .htaccess file in the Scalar root folder, and I believe "Fast CGI" is turned off because other .htaccess files in other root folders are working properly. I have multiple application root folders in my public_html folder at my cPanel File Manager. Do you think the installation location is creating the problem for the application?

Cheers,
Max

**Comment by craigdietrich** [comment]
Unfortunately, if .htaccess' are operational, I'm not sure why the routing isn't working.

Can you go ahead and email me at craigdietrich at gmail?  We can see if we can find the root of the problem.

**Comment by maxgray20** [comment]
Hi @craigdietrich,

Sounds good. Yes, I'll email you here now. Thank you very much! I appreciate it a lot.

Cheers,
Max
