### ISSUE TITLE
Problems with mobile display

### ISSUE THREAD

**Issue by EmilyMarsh** [anvc/scalar#173]
Hi

I have an external installation at https://scalar.emily-marsh.com/naldc.

The display on a laptop or monitor is fine.

The display on mobile (iPad) is not as good, however. The key images for the pages included in the relevant path appear distorted.

Here is a page formatted as a visual path.

On laptop:

![image](https://user-images.githubusercontent.com/5777982/127790648-f3436507-c286-401e-810f-34800a0b5a7a.png)

On iPad:

![image](https://user-images.githubusercontent.com/5777982/127790600-25b7675a-7b39-42a3-ad0e-d6f49ebc831d.png)

Is there anything I can do to improve the display on mobile?

The page in question is here: https://scalar.emily-marsh.com/naldc/introduction-and-overview?path=index.

Thanks, Emily

**Comment by eloyer** [comment]
@EmilyMarsh It looks like the mobile styles aren't being properly applied at larger sizes (the same issue occurs with a phone in landscape orientation). iOS doesn't support `background-attachment: fixed` which enables the "background stays put while everything else scrolls" effect, but images are also not scaling correctly to fit the size of the container element. Still assessing a fix.

**Comment by eloyer** [comment]
@EmilyMarsh We've got a fix for this that will roll out in the next update.

**Comment by EmilyMarsh** [comment]
Awesomeness. Thank you!
