### ISSUE TITLE
Reclaim hosting 2.5.17 > 2.6 update issues

### ISSUE THREAD

**Issue by michael-wynne-wsu** [anvc/scalar#174]
We've run into some issues with the latest update on Reclaim Hosting, and they suggested contacting y'all directly.

At the moment, all pages seem to have the dc:date field dropped from their metadata after running the 2.6 update. Not sure yet if there are other issues (we updated last week and the instance imploded, trying again from a restored backup).

Any information either to troubleshoot ourselves or pass on to Reclaim about this particular update would be very much appreciated.

**Comment by eloyer** [comment]
Sorry to hear that the upgrade hasn't gone well -- can you provide a link to the instance and some more details about it's current state? Did the date metadata disappear when you restored from backup, after you tried to update again, something else? It'd also be good to know more about specifically what you saw when the install "imploded". FWIW, our test Reclaim instance upgraded smoothly.

**Comment by michael-wynne-wsu** [comment]
Thanks Erik,

- Main instance is here: https://cdsc.libraries.wsu.edu/scalar 
- The book I'm working on currently isn't public, but can share elsewhere if needed.
- Happy to grab any relevant details from the instance or Reclaim as needed.

And the more detailed timeline:
- Site auto updated from 2.5.17 > 2.6, didn't notice any issues for a few days.
- After the 2.6 update, I created a timeline page, and created 50 pages connected to it. It displayed and worked well.
- About a day later, the timeline no longer displayed any entries, and on inspection all 50 pages no longer had a populated dc:date field.
- Shortly after that my main book began periodically displaying the error below when editing/saving pages.
- ![Screen Shot 2021-08-06 at 3 33 48 PM (2)](https://user-images.githubusercontent.com/88502274/129098155-0def7d2a-2479-4e7f-9cdd-3cdaa12d251d.png)
- Not long after that the entire book was unresponsive (screenshot below). And then the entire instance would throw an error when trying to login at all (I did not grab a message of that error specifically).
- ![Screen Shot 2021-08-11 at 9 03 50 AM](https://user-images.githubusercontent.com/88502274/129095826-ae3f1639-4d2a-44b2-8b0f-931fa9f3a407.png)
- At that point we restored the instance to the most recent 2.5.17 backup, and everything seemed normal.
- I turned off auto-updates, and continued to work on my main book. I recreated the exact same timeline, all good.
- Waited for the next auto-backup to generate, ran the update to 2.6. 
- Immediately after the update, the timeline tagged pages lost their dc:date field. 
- Restored back to 2.5.17 and have worked on that version for the last 2 days or so. 

Again, happy to collect any more relevant details, troubleshooting, etc.

Thanks!

**Comment by eloyer** [comment]
Thanks @michael-wynne-wsu , this is helpful. Could you DM us the URL for your book and your install's registration key on Twitter @anvcscalar or via email at alliance4nvc@gmail.com?
