### ISSUE TITLE
Mirador integration not functioning

### ISSUE THREAD

**Issue by waltster** [anvc/scalar#180]
I have been testing a Scalar instance and trying to use the Mirador viewer with a manifest. When I load it into the included viewer, it does not render the manifest content. To remedy the issue, I built my own `Mirador.min.js` and uploaded it to the Scalar instance and was able to get it working. I am wondering if this has been reported before? If so, is there a known fix?

The manifest is valid IIIF v3.

Included build of Mirador:
![Screen Shot 2021-10-30 at 12 50 43 PM](https://user-images.githubusercontent.com/12616796/139541971-e50eb427-4d89-413a-8ca3-8df2798d01ac.png)

My build of Mirador:
![Screen Shot 2021-10-30 at 12 52 11 PM](https://user-images.githubusercontent.com/12616796/139542024-619e217e-1d94-48ac-a073-88e38ddcbf3b.png)

**Comment by eloyer** [comment]
We haven't encountered this before — would you be willing to share your manifest for us to test with?

**Comment by waltster** [comment]
@eloyer sure, here it is!

```json
{
  "@context": "http://iiif.io/api/presentation/3/context.json",
  "id": "https://piranesi-test.reclaim.hosting/walts-test-book/media/Manifest_TomJerryV2.json",
  "type": "Manifest",
  "label": {
    "en": [
      "Tom and Jerry doing the whole like fighting thing."
    ]
  },
  "items": [
    {
      "id": "https://piranesi-test.reclaim.hosting/walts-test-book/media/testmanifest/canvas/p1",
      "type": "Canvas",
      "height": 3024,
      "width": 4032,
      "items": [
        {
          "id": "https://piranesi-test.reclaim.hosting/walts-test-book/media/testmanifest/page/p1/1",
          "type": "AnnotationPage",
          "items": [
            {
              "@context": [
                "http://www.w3.org/ns/anno.jsonld",
                "http://iiif.io/api/presentation/3/context.json"
              ],
              "id": "https://piranesi-test.reclaim.hosting/walts-test-book/media/testmanifest/annotation/p0001-image",
              "type": "Annotation",
              "motivation": "painting",
              "body": {
                "id": "https://env-4072537.us.reclaim.cloud/iiif/2/tomjerry.jpeg/full/full/0/default.jpg",
                "type": "Image",
                "format": "image/jpeg",
                "height": 168,
                "width": 300
              },
              "target": "https://piranesi-test.reclaim.hosting/walts-test-book/media/testmanifest/canvas/p1"
            }
          ]
        }
      ]
    }
  ]
}

```

**Comment by eloyer** [comment]
@dodget Would you mind taking a look at this? I can confirm the reported behavior. Perhaps the bundled player is due for an update?

**Comment by dodget** [comment]
@eloyer - I'll take a look and hopefully get it resolved by the end of the week!

**Comment by craigdietrich** [comment]
@eloyer @dodget 

Does @waltster's JSON load into the Mirador demo at https://mirador-dev.netlify.app/__tests__/integration/mirador/ ?

**Comment by waltster** [comment]
@craigdietrich @eloyer @dodget The JSON does load! Here's a [Gist with it](https://gist.githubusercontent.com/waltster/1830b76fb496d5d786d6900094b33887/raw/c8bcdf407ded7768f08868f74e17d1953d3399a3/gistfile1.txt) that you can use to test!

**Comment by eloyer** [comment]
Thanks so much @dodget !
