### ISSUE TITLE
Annotating PDF files.

### ISSUE THREAD

**Issue by schnydszch** [anvc/scalar#184]
Hi! I am trying to learn Scalar. I tried to search if there's a way to annotate PDF, it seems there is no way to annotate pdf. What I saw in https://scalar.me/anvc/features/annotations/ is that we are able to annotate "video, audio, images, source code, and text". By text here is the html text. I've tried hypothes.is, I cannot also see a '"'  button when highlighting text in the pdf file. Please advise if I am missing something? Kudos!

**Comment by eloyer** [comment]
Hi @schnydszch , you are correct, there's currently no way to annotate a PDF in Scalar.
