### ISSUE TITLE
Playing Youtube Scalar Media

### ISSUE THREAD

**Issue by schnydszch** [anvc/scalar#188]
I am trying out Scalar Media Link. I have youtube videos added as media but they have the same video source, only differentiated by the start and end time (e.g. https://youtu.be/ECXkBgDfvts?start=2130&end=2354 and https://youtu.be/ECXkBgDfvts?start=1662&end=2120). The thing is if the videos are played, whatever was the last timestamp for a particular youtube media, that timestamp is assumed even though the youtube video link has its own start time. Is there a way for Scalar to assume instead the URL parameter for start time which in my example are 2130 (35:30) and 1662 (27:42)?

**Comment by eloyer** [comment]
@schnydszch We've got a fix, need to do some testing and then we'll update our install.

**Comment by schnydszch** [comment]
@eloyer  Thanks for the fix! How do I add the patch to my current install? Or will just wait for the updated version. Thanks again!

**Comment by eloyer** [comment]
@schnydszch Are you running your own install, or are you on Reclaim?

**Comment by schnydszch** [comment]
@eloyer I am running on my own.

**Comment by eloyer** [comment]
@schnydszch You can just update from the repo, we haven't seen any issues in testing.
