### ISSUE TITLE
Registration Key for scalar.edu

### ISSUE THREAD

**Issue by Austin122334** [anvc/scalar#191]
Hi there, I'm unable to DM to scalar. I've been trying to get a registration key for a few weeks. Sent in the form but no reply. Could you please advise? I need a registration key.
 Thanks!

**Comment by eloyer** [comment]
@Austin122334 If you follow the instructions at https://scalar.me/anvc/contact/ then we can help.

**Comment by Austin122334** [comment]
I have tried many times but unfortunately failed to contact.

**Comment by eloyer** [comment]
Have you tried emailing us directly using the address on that page, instead of using the form?

**Comment by Austin122334** [comment]
Yes, i have tried many times.

**Comment by eloyer** [comment]
If you are not able to email us at alliance4nvc@gmail.com from an email address affiliated with an academic or cultural institution, with a description of your planned uses for Scalar, then we are unable to provide a registration key. Please refrain from creating future issues on this topic.
