### ISSUE TITLE
Editorial workflow editor Accept changes?

### ISSUE THREAD

**Issue by apjmason** [anvc/scalar#198]
Is it possible for Editors to approve changes and override the Edit Review stage if Authors are non-responsive?

I'm using the Editorial workflow (which is great!) for a class project in which students authored pieces. Now the term has ended and I can't guarantee student authors will act to approve changes and move it to the Clean state. How can I override?

Thanks!

**Comment by eloyer** [comment]
Glad the workflow has been useful! There isn't a direct way to do this, but there are two workarounds. One is to create another author user for yourself to approve the changes. Another would be to turn off the workflow entirely (which we'd only recommend if you're not planning to make any further edits).

**Comment by apjmason** [comment]
Oh, I see. Any author can approve any changes in the Edit Review state! I thought it would only allow the original content author to approve. A separate author user is fine for this. Thanks!
