### ISSUE TITLE
Centralized authentication mechanism

### ISSUE THREAD

**Issue by ccc2lu** [anvc/scalar#20]
Is there a way to have our own hosted instance of Scalar use our campus CAS or an LDAP server for authentication of users?  It's fine with me if users still have to register for an account in Scalar before logging in, but I want the actual authentication to be done by one of these external authentication mechanisms.  I couldn't find any configuration options or plugins that handle this when setting Scalar up on my server.
Thanks,
-Chris Creswell

**Comment by craigdietrich** [comment]
We haven't added any login hooks to Scalar other than what is presently in the login model (which hits the users table in the database):

https://github.com/anvc/scalar/blob/master/system/application/models/login_model.php

We've had our sights on incorporating a federated login (for Google+, FB, etc), but so far haven't made movement on this front.  Though I imagine it wouldn't be too difficult to extend the login model to validate against your campus server before returning 'true' inside do_login()?

Thanks for your interest,
Craig
