### ISSUE TITLE
New tags do not save and existing tags disappear

### ISSUE THREAD

**Issue by srob4757** [anvc/scalar#200]
I have a Scalar 2.6.2 install on Reclaim Hosting that has stopped saving tags: I can sometimes get up to 5 tags on a page to save without an issue, but if I save a page with 6 or more tags, additional tags do not save and some existing tags disappear every time I save. I have worked with Reclaim to restore multiple backups, but the problem persists. During the save the count of relations hangs briefly at 5. This is a large project for which I have impending deadlines, so I have also tried to export the content as RDF-JSON to move it to a new install, but the export does not work, ending with a 503 error.

**Comment by mmcloe** [comment]
@srob4757 hi! Did you ever manage to resolve this. I'm having a similar issue with adding to paths.

**Comment by srob4757** [comment]
My problem seems to have been with the install on Reclaim Hosting - a WordPress site was somehow interfering with the Scalar site. Moving the site to another domain has fixed it for now

**Comment by mmcloe** [comment]
Thank you!
