### ISSUE TITLE
Error when adding items to a path

### ISSUE THREAD

**Issue by mmcloe** [anvc/scalar#201]
I am running Scalar 2.6.2 on Reclaim Hosting and am no longer able to to consistently add items to a path anymore. Adding items to a path results in a 404 error message and deletes most of the path items on the page, forcing me to install previous versions of the page. There doesn't seem to be any pattern as to which pages successfully add to a path and which fail, but I have noticed that difficulties arise more commonly around six or so added pages.

**Comment by eloyer** [comment]
As you saw in the comments on the other issue, we've seen a similar problem triggered by having an active WordPress install on the same Reclaim account. Is that the case for you?

**Comment by mmcloe** [comment]
I believe this is the same issue, yes. I talked with some folks at Reclaim Hosting and they suggested that I clone my site to a separate domain. Unfortunately, it doesn't seem like Scalar is an application that can be cloned.

**Comment by mmcloe** [comment]
Update: I just moved my Scalar site to a new subdomain on Reclaim Hosting, the problem is still persisting.

**Comment by eloyer** [comment]
Can you reach out to us at alliance4nvc@gmail.com and provide the URL to your project so we can take a look?

**Comment by eloyer** [comment]
Moving the project to a new server on Reclaim appears to have solved the issue, closing.
