### ISSUE TITLE
Deprecated package yepnope v1.5.3

### ISSUE THREAD

**Issue by Tanvez** [anvc/scalar#208]
We saw that the [yepnope](https://github.com/SlexAxton/yepnope.js) package/script is not currently maintained(last tagged version was v2.0.0 - updated in 2014). So we wanted raise an issue about future plans for the package/script. [Places](https://github.com/search?q=repo%3Aanvc%2Fscalar%20yepnope&type=code) where the package is being used currently 

We ran across this package/script because we were running into some issues where pages would inconsistently throw errors like `Uncaught TypeError: Cannot read properties of null (reading 'insertBefore')`. This error is likely due to `yepnope` not being loaded/available for use when the application first invokes/uses any of `yepnope` functions/methods. We have since updated the version on our fork to `v1.5.4` to hopefully mitigate the issue.

 Example of Error:
<img width="1662" alt="Screen Shot 2023-03-24 at 5 47 55 PM" src="https://user-images.githubusercontent.com/29421667/228325103-6b47b28d-66e3-4c6f-ac6c-eec3569419b4.png">

**Comment by NumerousHats** [comment]
I realize this is a stale issue, but I'm suddenly seeing this same problem (`Uncaught TypeError: Cannot read properties of null (reading 'insertBefore')`) even with yepnope v1.5.4 on Firefox Linux and Windows (but not on Android, curiously). The result is a visually completely blank page, so it's kind of a major problem. How difficult would it be to eliminate yepnope? I'm not a JS guy, so I have no clue.

I can open a new issue if appropriate.

**Comment by craigdietrich** [comment]
Yep, I think I can replace yepnope, as mentioned earlier in this thread I think it's just a matter of replacing yepnope called with $.get calls.  I'll see if I can get to it this week!

**Comment by craigdietrich** [comment]
@NumerousHats Here ya go:  https://github.com/anvc/scalar/commit/e317c1d0528c822cf93a2ba180e68dfef4cd62fd ... this removes yepnope from Cantaloupe! 

You may have some problems early on if main.js is cached in your browser, so I'd recommend clearing your browser cache.
