### ISSUE TITLE
getting error message on scalar home page

### ISSUE THREAD

**Issue by rcrath** [anvc/scalar#21]
Hi, sometimes scalar will show a page with a short text saying the site is unavailable.  I cannot remember the exact phrasing.  Deleting cookies for the site restores it.  It seems to be something to do with multiple people either working on the same book or same doc, but not sure about that.  I can provide more details as needed, but the occurrence is semi-random, so it might take a while to repeat it.  Not sure what version of scalar it is but installed it this semester so fairly recent.

**Comment by rcrath** [comment]
Here is the message we get (courtesy of a student who just got locked out!) 

blank page with 'Disallowed Key Characters' in the top left corner"

**Comment by craigdietrich** [comment]
Hi Rich,

You've encountered a protective layer in CodeIgniter (Scalar's underlying framework) that is a little too picky: there's a function that looks at the field names of incoming cookies and will display the error message and halt the application if there are special characters (e.g. ~ or @, etc).  There's a few spam tracking cookies out there that can invoke this.

Are you using Scalar on our server (scalar.usc.edu)?  If so, we already put in a patch that corrects this, so if the problem persists it means the patch needs enhancements and I can work to make it better.

Though, if you're using Scalar on your own server, the patch is to overwrite this file:  "system/libraries/Input.php" in your Scalar root folder with: https://github.com/anvc/scalar/blob/master/system/libraries/Input.php

Thanks,
Craig

**Comment by rcrath** [comment]
THanks Craig, We are running our own instance.  I updated Input.php, and the site stayed up, so I assume we can close this issue.
