### ISSUE TITLE
Resizing window duplicates inline notes

### ISSUE THREAD

**Issue by novomancy** [anvc/scalar#215]
We've noticed that resizing the browser window causes inline notes to duplicate. You can see the effect here:

<img width="833" alt="Reproduced Quotes Bug" src="https://github.com/anvc/scalar/assets/392376/8abde1cf-cb46-4692-8f06-698818ea438e">

This appears to happen in Mac and Win, and we've tested on Chrome and FF.

**Comment by craigdietrich** [comment]
Hi John,

Seems like a simple enough fix (updating the event to resize instead of redraw).  I'll take a close look shortly.

**Comment by craigdietrich** [comment]
For anyone encountering this thread, it was resolved with this commit:

https://github.com/anvc/scalar/commit/d057efbdb4ec8855db1c14179d2e7df0201889c8
