### ISSUE TITLE
A PHP Error was encountered

### ISSUE THREAD

**Issue by mat-k-witts** [anvc/scalar#219]
![php](https://github.com/anvc/scalar/assets/83780461/33d80493-0c39-4369-bdbe-d7246eafaeea)

**Comment by mat-k-witts** [comment]
phpseclib and mcrypt incompatibilty issue with 8.1 - rolling back to 8.0 fixed it.

**Comment by craigdietrich** [comment]
Actually, I think PHP 8.1 should work fine, but you need to set "development" to "production" in:

<scalar root>/codeigniter.php

... which suppresses PHP warnings.

**Comment by mat-k-witts** [comment]
Possibly... (coincidentally?) Installatron backups resumed normally operation on rollback to 8.0. Just saying. Sorry, don't have time to see if this is reproducible.
