### ISSUE TITLE
Error when importing book to custom install

### ISSUE THREAD

**Issue by sukelully** [anvc/scalar#225]
Hi,

I recently installed Scalar on my own server and am trying to import my book from Scalar's own server. The content seems to import correctly but unfortunately none of the relationships are carried over. The error(s) I'm given is:

_URL isn't a Scalar Save API URL [https://the-digital-baermann.hosted.york.ac.uk/test/api/add] for "Heinrich Baermann to Felix Mendelssohn-Bartholdy, 16 September 1834"_

The URL of this page is in the original book is: _https://scalar.usc.edu/works/the-digital-baermann/felix-mendelssohn-bartholdy-to-heinrich-baermann-31-july-1831_

And here is a screenshot of the import window and errors: 
<img width="643" alt="Screenshot 2024-01-11 at 14 02 54" src="https://github.com/anvc/scalar/assets/78022109/97a2ae65-355f-41c3-87d3-c1e909182ab4">

I've trawled through the issue tracker and user's guide but can't seem to find anything relevant. Anything I'm missing? Thanks!

**Comment by craigdietrich** [comment]
Hi @sukelully 

Sorry you've run into this problem!  Admittedly, this isn't an error that comes up very often so I might not have the best advice on how to fix. 

That said, can you email me at craigdietrich at gmail and I can help from there?
