### ISSUE TITLE
Blank Error Page on install

### ISSUE THREAD

**Issue by paulshannon** [anvc/scalar#29]
Trying to set up a docker based install and running into a blank page. Any thoughts on what is wrong or how to get it to spit out an error (or where it might be pitting out an error) would be appreciated.

I've tried setting `$config['log_threshold'] = 0;` in `system/application/config/config.php` to values 1,2,3 and 4 but there is no effect.

--

If you're not familiar with docker, it is basically just a way of building very lightweight virtual machines.

The the file below defines what is done on top of a base image to build what you're looking for. I've added some comments in the file below reflecting what is going on.

It starts with this docker supplied php file:
https://raw.githubusercontent.com/docker-library/php/7bd5c38db974ee629a815896add1ec568a1cc88c/5.6/apache/Dockerfile

Which is basically just an apache and php install on top of a barebones debian base. Then my Dockerfile

DockerFile:

```
FROM php:5-apache

MAINTAINER paul.shannon@carleton.ca

# Setup; updates packages
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get -q -y upgrade

# Apache; enables mod_rewrite
RUN a2enmod rewrite

# PHP; install mbstring and mysql extensions
RUN docker-php-ext-install mbstring
RUN apt-get -q -y install php5-mysql


# Scalar; downloads the code from the git repo
RUN apt-get -q -y install git
RUN rm -R /var/www/html/
RUN git clone https://github.com/anvc/scalar.git /var/www/html/

# Copies my custom php.ini file
COPY php.ini /usr/local/etc/php/
```

php.ini

```
short_open_tag = true

date.timezone = "US/Eastern"
```

**Comment by craigdietrich** [comment]
Can you send a message here, attention me (Craig): 

http://scalar.usc.edu/contact/

This way we can shoot some emails back and forth?

**Comment by paulshannon** [comment]
Something was eating up my error logs. I finally was able to generate this.
```
PHP Fatal error:  Call to a member function result() on a non-object in /var/www/html/system/application/models/book_model.php on line 381

PHP Fatal error:  Call to a member function result() on a non-object in /var/www/html/system/application/models/book_model.php on line 685
```
From the index page on a fresh install.

**Comment by paulshannon** [comment]
The sql script wasn't installing correctly (but didn't throw an error in my build process).

May I suggest that having the application in that state should not lead to a blank screen?

Sorry for the noise.

**Comment by craigdietrich** [comment]
@paulshannon Do you have a recommended way to do this?  Does it involve placing  ini_set('display_errors', 1); error_reporting(E_ALL); etc in CodeIgniter's error handling method, do you think?

**Comment by plusperturbatio** [comment]
@craigdietrich What's weird about this is that if you look at the index.php file, it has the line, "error_reporting(E_ALL);" - CodeIgniter also has its own error formatting page for when a PHP error is thrown. I suspect that in @paulshannon 's case (correct me if I'm wrong, Paul), the php.ini settings are set such that errors are not displayed.

This could be corrected with ini_set('display_errors', 1) , though that may provide some unwanted output for people who manually went through and changed their php.ini settings.

An option that I've seen on other sites might be to make another local settings item (called "environment" or something similar) that, when set to "development" enables display_errors and E_ALL reporting, while an environment of "production" disables errors except for in logs (or just leaves those settings alone, to be dealt with in the php.ini file.)

Just a couple of other thoughts on the matter!

**Comment by craigdietrich** [comment]
Is it true that in the case there's some core problem (like MySQL not hooking up), even with error reporting properly turned on and the error level > 0 in the config, that no errors display or get logged, @paulshannon?

But I like the idea of maybe having a "development" vs "production" bit ... we could even extend this to the config files themselves (I think you've mentioned this before, @plusperturbatio).

**Comment by paulshannon** [comment]
I think that is the case. I'm not familiar with codeigniter though. What settings should be enabled to throw show the errors?
