### ISSUE TITLE
Multiple author credits

### ISSUE THREAD

**Issue by complexfields** [anvc/scalar#3]
For books with multiple authors, it would be great to be able to see who authored what material, both on individual pages and in visualizations for the book. 
The information seems to be there in the edit history for individual pages. Though we know that a page will store an author as having edited the page even if she only made a typo correction, would be better to just include every author who "touched" a page/object and then perhaps allow for edits after the fact (some sort of "remove author from this page" option perhaps).

**Comment by craigdietrich** [comment]
@complexfields This is now a thing!  Scalar 2 Custom JS: http://scalar.usc.edu/works/guide2/revealing-individual-authors-in-page-headers?path=advanced-topics
