### ISSUE TITLE
Way to turn off comments by default?

### ISSUE THREAD

**Issue by ccc2lu** [anvc/scalar#43]
A user at Lehigh University wants to know if there's a way to disable comments by default for newly published pages.  Can this be done at the page or book level?

**Comment by craigdietrich** [comment]
Hi @ccc2lu,

In Dashboard > Sharing one can force comments to be moderated, in which case they will be hidden in the book until an author "approves" it (by setting it live in Dashboard > Relations > Comments).  Is this sufficient?

The comment thought bubble icons at the bottom of every Scalar page can be hidden by CSS, which is probably the easiest/best option to simply remove commenting all together.

Note that, like all things Scalar, comments are themselves pages.  So one can create comments alternatively by creating a page then clicking, "To make this page a comment, select pages that it comments on" under the page editor's relationships tab.

Curious your thoughts?
