### ISSUE TITLE
"No input file specified." when clicked on Register/Login

### ISSUE THREAD

**Issue by tuxnani** [anvc/scalar#46]
Hello, 

I have an instance of scalar installed at http://rahman.veeven.com/scalar/
When I click on Register or Login, I get a page with "No input file specified." and nothing else. 
What might be wrong?

**Comment by craigdietrich** [comment]
Hi @tuxnani,

Is there a chance you're hosting on GoDaddy?  If so, I think a small change needs to be made to the .htaccess file in the Scalar root folder: http://stackoverflow.com/questions/6118740/codeigniter-no-input-file-specified

Let me know if this is the case?  If not, I'm happy to further assist!

**Comment by tuxnani** [comment]
The hosting is on hostgator. and the directory structure is something like

/
|- public_html
|  | -  base site
|  |   | - scalar
|  |   |  |- .htaccess
|  |   |  L- codeigniter.php


Should I put .htaccess in base folder instead?

**Comment by craigdietrich** [comment]
@tuxnani the .htaccess file, and all of the files that are in the root folder  here:https://github.com/anvc/scalar , definitely, should all be in the same root folder on your server...
