### ISSUE TITLE
Scalar 2 Google Map Layout Page Problem

### ISSUE THREAD

**Issue by jskirby2** [anvc/scalar#47]
I'm not very good with web design stuff and I'm not sure if this is where I'm supposed to put these types of questions but in the last three days I have been tried to create a page using the Google Map layout and whenever I try to add spatial metadata the page says it's saving but never fully saves, then when I leave the page it messes up what I had done before. For example, it made a version of the page where the page no longer annotated two media files and took the page off of the path it was part of. I am using the WYSIWYG editor on Firefox/Chrome though I did try to add my own custom CSS/Javascript though I have since deleted these features from my pages. 
 Scalar 2 has also been randomly signing me off before I was able to save changes and creating a site on here has been a very frustrating experience. I don't know what is going on.

**Comment by craigdietrich** [comment]
@jskirby2  Hi!

Thanks for your note, and sorry to hear about the hiccups.  We've had some reported issues with saving and logout issues since the weekend, which we're trying to address.  I suspect this is related.

Can you send details, including your Scalar book URL, to scalar.usc.edu/contact?

Thanks!

**Comment by jskirby2** [comment]
Everything is working a lot better today thank you!

**Comment by craigdietrich** [comment]
@jskirby2 Great to hear!  I pushed live an update last night that corrected what I think was the root of the logout problems.  I also noticed that the Semantic Web (metadata) tables were having problems, so I repaired them.  I'm keeping an eye on things hoping more problems don't crop up.  Definitely let me know if they do!

Thanks,
Craig
