### ISSUE TITLE
Scalar and Firefox problems?

### ISSUE THREAD

**Issue by jskirby2** [anvc/scalar#48]
Hi!
I tried to sign on http://scalar.usc.edu/    using Firefox (pretty close to default version of Firefox with a few plugins from Adobe and MS Office) and it leads to a 404 Not Found page. I am signed in when I go to the page for the book and I can sign in with Chrome fine. Is Chrome the recommended browser for Scalar? Are there browsers that are preferred/ should be avoided? Any information would be great thanks!

**Comment by craigdietrich** [comment]
Hi @jskirby2,

All browsers should behave the same.  It could be that your Firefox has something cached that is impacting it's ability to load the login page.  Maybe try clearing your browser history, then trying again?

Here's a shortcut to the login page:
http://scalar.usc.edu/works/system/login

Cheers,
Craig

**Comment by jskirby2** [comment]
Yup, that seems to have fixed the problem. Thanks!

**Comment by craigdietrich** [comment]
You bet!
