### ISSUE TITLE
HELP HELP!!!  Scalar redirects back to login screen after I log in

### ISSUE THREAD

**Issue by pguerr061703** [anvc/scalar#49]
I have a problem with scalar. It keeps REDIRECTING me to login screen after I LOG IN.
I  am never LOGGED IN (in scalar). 
My virtual host is NOT using SSL. Strictly standard virtual host with port 80 listening
I am using the default .htaccess (that came with scalar) in my /var/www/html/scalar directory.
On a Redhat virtual host.

Can someone please help me find out WHY this is HAPPENING?
I really need to get this working for faculty by tomorrow. Some information on it below

I enabled php (mbstring module as mentioned in the INSTALL.txt)

PHP version is 5.3
[root@ace-linux11 conf]# php -v
PHP 5.3.3 (cli) (built: Jul 25 2016 05:47:24)
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies
[root@ace-linux11 conf]#

Snippet of /etc/httpd/conf/httpd.conf
<VirtualHost *:80>
    DocumentRoot /var/www/html/scalar
    ServerName scalar.ace.fordham.edu

```
  <Directory /var/www/html/scalar>
       Options Indexes FollowSymLinks
       AllowOverride All
       Order allow,deny
       allow from all
 </Directory>
```

</VirtualHost>

**Comment by plusperturbatio** [comment]
Hey there, sorry this is a bit late getting back to you but - could you make a PHP file somewhere on your server that you can access with the following contents:

`<?php

phpinfo();

?>`

Once this is made, go to that page. You should get a purple and grey information page detailing your server's PHP installation. Search for the word, "Session" - there should be a section containing the item, "Session Support." Can you confirm that it says "enabled" ?

Also, do you have any errors or warnings in your PHP or Apache logs? The log files are likely located in one of the following locations:
/var/log/apache/
/var/log/httpd/
/var/log/apache2/

Thanks!
Lucas

**Comment by akprtll** [comment]
I'm experiencing the same problem with recurring redirecting-- from .../scalar/system/login?redirect_url=%2Fscalar%2F to (when I click "Sign in")  .../scalar/system/login?redirect_url=%2Fscalar%2Fsystem%2Flogin%3Fredirect_url%3D%252Fscalar%252F, etc. The site was working great just a few days ago and I hadn't changed anything in the intervening days. I created a phpinfo file and Session Support is "enabled". What steps might I try next?

**Comment by craigdietrich** [comment]
What hosting are you using?

**Comment by akprtll** [comment]
My site is on Reclaim Hosting.

**Comment by craigdietrich** [comment]
Ah, yep, that's the fix!   This would be the same fix if you had contacted Reclaim support directly, @akprtll

**Comment by akprtll** [comment]
Thanks so much @sfrielick! That fix worked perfectly. I was able to install a new copy of Scalar on my Reclaim Hosting site so I hadn't been sure if it was an issue at the hosting level or the program level.
