### ISSUE TITLE
LacunaStories -  update to Drupal 7.5.1 

### ISSUE THREAD

**Issue by pguerr061703** [anvc/scalar#50]
Hello,
I am running LacunaStories on  Drupal core 7.5.0 on a Ubuntu 16.04 virtual host.
When I click on  Report-->Status Report , I noticed that Drupal 7.5.1 is available.
Can someone let me know how I can perform this update manually? 
Will  LacunaStories work on 7.5.1 ? Anything to look out for?
I already backed up the database (via Backup and Migrate).

Thank you

**Comment by eloyer** [comment]
Hi @pguerr061703, this is the issues forum for Scalar—I think you may be looking for this forum instead: https://github.com/PoeticMediaLab/LacunaStories/issues
