### ISSUE TITLE
Reset password in scalar not working

### ISSUE THREAD

**Issue by pguerr061703** [anvc/scalar#52]
I can't seem to reset my password in scalar. As soon as I click forgot password and enter my email address and click "reset password" ...nothing happens.

Scalar is not doing anything...just waiting.

**Comment by craigdietrich** [comment]
Scalar uses SMTP to send emails if configured to do so, so I'm guessing either a) you've entered SMTP fields into config/local_settings.php, but your server doesn't have SMTP turned on; b) SMTP settings haven't been added to config/local_settings.php, in which case Scalar will revert to PHP's mail() function, which is sketchy at best....

**Comment by craigdietrich** [comment]
If push comes to shove you should be able to simply delete the value of 'password' in the users table of the database (e.g., in phpMyAdmin), in which case Scalar should prompt you to add one when you try to log in again.

**Comment by pguerr061703** [comment]
Can you confirm if the smtp port needs to be in single quotes '465' or without  single-quotes 465 below ? BTW I substituted '<my###>'  for privacy
This should be working ...but its nothing happens. I confirmed smtp is setup and mail (sendmail) works on the server.

$config['smtp_host'] = '<mysmtp_server>.fordham.edu';
$config['smtp_auth'] = 'true';
$config['smtp_username'] = '<myserver>@fordham.edu';
$config['smtp_password'] = '<mypassword>';
$config['smtp_secure'] = 'ssl';
$config['smtp_port'] = 465;

**Comment by aaliceeee** [comment]
http://www.passwordmanagers.net/resources/Best-iphone-data-recovery-software-18.html
password manager for Windows systems

**Comment by craigdietrich** [comment]
@pguerr061703 I might suggest removing the SMTP fields and setting 'smtp_auth' to false, to test to see if your server's PHP mail() function works .. who knows, it could work just fine for fordham's email system.

Back to SMTP: what do the logs say (if anything)?
