### ISSUE TITLE
Scalar messages in system/application/logs

### ISSUE THREAD

**Issue by pguerr061703** [anvc/scalar#53]
Seeing these errors in /var/www/html/scalar/system/application/logs 
Can you let me know what is causing this.
I have at least 20 users on my Redhat6 scalar server.
Thank you.

ERROR - 2016-11-17 21:38:56 --> Severity: Notice  --> Trying to get property of non-object /var/www/html/scalar/system/application/views/modules/dashboard/book_style.php 19
ERROR - 2016-11-17 21:38:56 --> Severity: Notice  --> Trying to get property of non-object /var/www/html/scalar/system/application/views/modules/dashboard/book_style.php 222
ERROR - 2016-11-17 21:38:56 --> Severity: Notice  --> Trying to get property of non-object /var/www/html/scalar/system/application/views/modules/dashboard/book_style.php 249
ERROR - 2016-11-17 21:38:56 --> Severity: Notice  --> Trying to get property of non-object /var/www/html/scalar/system/application/views/modules/dashboard/book_style.php 252

**Comment by craigdietrich** [comment]
These are only notices, I would ignore them.  It's PHP saying that a couple variables are empty when trying to be used in context.  (Technically we could clear these out but it's low priority.)
