### ISSUE TITLE
Media Import issue within Scalar

### ISSUE THREAD

**Issue by pguerr061703** [anvc/scalar#54]
why the Media Import feature of Scalar routinely gives Internal Server error messages when you try to import from partner archives.

In Scalar, if you you are in a book (from tech professor:  shill18@fordham.edu has), and you go to the Import Option:
and try to get anything from Affiliated Archives, or Other Archives:
( try searching for Picasso, at the Met, for example,) you get:
"Internal Server Error"---> See picture attached
![internal_server_error]
(https://cloud.githubusercontent.com/assets/12171475/20438158/89a6a20e-ad84-11e6-813a-3d94809e897d.png)

The other two options work:  Local Media Files and Internet Media Files both work just fine.

Thank you,
Patrick

**Comment by craigdietrich** [comment]
Is the .htaccess file present in system/application/rdf?

https://github.com/anvc/scalar/blob/master/system/application/rdf/.htaccess

It's critical to allow requests through to the RDF proxy ... a lot of times the file doesn't get copied especially if you're using a Mac FTP client, where dot files are hidden.

**Comment by pguerr061703** [comment]
.htaccess is present.(see below)   Is this a possible firewall issue? ports that may need to be opened?
My Scalar server sits on a DMZ network.

# cat .htaccess
Satisfy Any
Allow from all# pwd
/var/www/html/scalar/system/application/rdf
#

**Comment by craigdietrich** [comment]
Hmm... I don't know much (if anything) about DMZ .... can you open up your browser's NET console and see what the http error number + message is when you try to search for something?

**Comment by clueboy37** [comment]
I'm experiencing something similar with affiliates and other archives. 

When searching the http result is a 404 error for my server, not the affiliate. "The requested URL /system/application/rdf/proxy.php was not found on this server." proxy.php is on the server, the path leading to it is accessible to the web server. The .htaccess file is present in system/application/rdf.

I'm running 2.1.1 on RHEL 6 with MySQL 5.5, Apache 2.2 w/ SSL, and PHP 5.3.3.

From Chrome's console: Request URL:https://sislt-scalar.missouri.edu/system/application/rdf/proxy.php?xsl=https%3A%2F%2Fsislt-scalar.missouri.edu%2Fsystem%2Fapplication%2Frdf%2Fxsl%2Fcuban_theater_digital_archive.xsl&uri=http%3A%2F%2Fctda.library.miami.edu%2Fobjsearch%2F%3Fq%3DBERNARDA&format=json&header=

httpd log entries from server:

Accessed Directly (visited: https://sislt-scalar.missouri.edu/system/application/rdf/proxy.php):
xxx.xxx.xxx.xxx - - [22/Nov/2016:12:08:47 -0600] "GET /system/application/rdf/proxy.php HTTP/1.1" 404 323 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36"

Accessed through Scalar:
xxx.xxx.xxx.xxx - - [22/Nov/2016:12:09:04 -0600] "GET /system/application/rdf/proxy.php?xsl=https%3A%2F%2Fsislt-scalar.missouri.edu%2Fsystem%2Fapplication%2Frdf%2Fxsl%2Fcuban_theater_digital_archive.xsl&uri=http%3A%2F%2Fctda.library.miami.edu%2Fobjsearch%2F%3Fq%3DBERNARDA&format=json&header= HTTP/1.1" 404 323 "https://sislt-scalar.missouri.edu/test-book/import/cuban_theater_digital_archive" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36"

**Comment by craigdietrich** [comment]
@clueboy37 ... and you're sure mod_rewrite (which enables .htaccess) is On in your apache config?

Your Scalar URLs are "clean", correct?   If not, for example, if page URLs have "codeigniter.php" in them, then this means the root .htaccess isn't working either.

**Comment by aarondmoss** [comment]
mod_rewrite is enabled. I just used it to send everyone to the maintenance page. I'm using version 2.1.2 now.
