### ISSUE TITLE
paths missing on image header layout

### ISSUE THREAD

**Issue by rcrath** [anvc/scalar#56]
Hi, When we use the image header layout, the paths are not included at the bottom of the page.  Is there any way to include the paths?

**Comment by craigdietrich** [comment]
Hi @rcrath, path contents should be displayed on the bottom of a page regardless of the Layout.  Here is an example of it working properly:

http://scalar.usc.edu/works/page-layout-examples/image-header-layout

Maybe send us details at http://scalar.usc.edu/contact and we can try to diagnose the issue?

**Comment by rcrath** [comment]
Hi @craigdietrich 
will followup by contacting you. might be an upgrade issue.

**Comment by rcrath** [comment]
@craigdietrich I followed up with an email a few days ago but have not heard back.

**Comment by craigdietrich** [comment]
@rcrath I'm not sure what happen, I checked in with our program manager an no email made it through.  Can you send me an email directly?  It's my GitHub username at gmail.

**Comment by rcrath** [comment]
sorry for lack of followup on this @craigdietrich -- we solved it with a new install.
