### ISSUE TITLE
I can't get your site to load!

### ISSUE THREAD

**Issue by murrayLuke** [anvc/scalar#58]
Currently having issues with your site at this link http://scalar.usc.edu/scalar/ 

I can't get it to load due to timeout errors, and this was the only place I could find to get in touch with your project.

**Comment by cfletche** [comment]
Hi Luke,


Yes there is a campus-wide network outage. University IT is working on the issue right now. Sorry for the inconvenience.


ANVC Team




________________________________

**Comment by murrayLuke** [comment]
good to hear. Will close this now.
