### ISSUE TITLE
Unable to Import SQL files

### ISSUE THREAD

**Issue by cppdigital** [anvc/scalar#69]
I've tried importing both SQL files (each with the proper collation) using both the command line and PHPMyAdmin but keep getting the following error:

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-----
CREATE TABLE IF NOT EXISTS `scalar_db_books` (
  `book_id` int(10) unsigne' at line 1

I could edit the SQL, but am worried that the database will be built wrong if I do. Is there an issue with SQL files in the most recent release? Or perhaps the necessary version of MySQL could be stated in the install.txt?

Thanks!

**Comment by craigdietrich** [comment]
Hiya!

Are you using the SQL file from Scalar 2.1.5?  If so, I think some ill-formatted comments got committed to that version.  Go ahead and try the live version here:

https://github.com/anvc/scalar/tree/master/system/application/config

Let me know how that goes?

**Comment by cppdigital** [comment]
That was it! Ok, thanks so much. Sorry for such a simple troubleshoot on the issues page, just didn't know where to reach out for help.

Best,

Tristan

**Comment by craigdietrich** [comment]
No problem!  Thanks for your interest in Scalar!
