### ISSUE TITLE
SSL using Scalar

### ISSUE THREAD

**Issue by pguerr061703** [anvc/scalar#70]
Hello,
 
On my virtual Redhat VM server, my Scalar site is giving me "404 Page Not Found" in the error log ("/var/www/html/scalar/system/application/log/log-2017-07-05.php")

When I go to http://scalar.domainnname.edu, I get the scalar HOME screen, but as soon as I click "Sign-In" link,the page does NOT render.  I get an "HTTP ERROR 500". 

This page isn’t working.
https://scalar.domainname.edu is currently unable to handle this request.
HTTP ERROR 500

 Is this an SSL thing ?? Can someone please help me asap?  Thank you

ERROR - 2017-07-05 00:21:59 --> 404 Page Not Found -->
ERROR - 2017-07-05 00:22:23 --> 404 Page Not Found -->
ERROR - 2017-07-05 00:22:25 --> 404 Page Not Found -->
ERROR - 2017-07-05 00:22:34 --> 404 Page Not Found -->
ERROR - 2017-07-05 00:22:36 --> 404 Page Not Found -->
ERROR - 2017-07-05 02:51:02 --> 404 Page Not Found -->
ERROR - 2017-07-05 08:40:13 --> 404 Page Not Found -->

**Comment by pguerr061703** [comment]
I see the error now, but not sure how to fix it


170216 11:39:25 [ERROR] /usr/libexec/mysqld: Incorrect key file for table './scalar_store/scalar_store_o2val.MYI'; try to repair it
170216 11:39:25 [ERROR] /usr/libexec/mysqld: Incorrect key file for table './scalar_store/scalar_store_o2val.MYI'; try to repair it
170216 11:39:25 [ERROR] /usr/libexec/mysqld: Incorrect key file for table './scalar_store/scalar_store_o2val.MYI'; try to repair it
170216 11:39:25 [ERROR] /usr/libexec/mysqld: Incorrect key file for table './scalar_store/scalar_store_o2val.MYI'; try to repair it
170216 11:39:25 [ERROR] /usr/libexec/mysqld: Incorrect key file for table './scalar_store/scalar_store_o2val.MYI'; try to repair it
170216 11:39:25 [ERROR] /usr/libexec/mysqld: Incorrect key file for table './scalar_store/scalar_store_o2val.MYI'; try to repair it
170216 11:39:25 [ERROR] /usr/libexec/mysqld: Incorrect key file for table './scalar_store/scalar_store_o2val.MYI'; try to repair it
170216 11:39:25 [ERROR] /usr/libexec/mysqld: Incorrect key file for table './scalar_store/scalar_store_o2val.MYI'; try to repair it
170216 11:39:25 [ERROR] /usr/libexec/mysqld: Incorrect key file for table './scalar_store/scalar_store_o2val.MYI'; try to repair it
170216 11:39:25 [ERROR] /usr/libexec/mysqld: Incorrect key file for table './scalar_store/scalar_store_o2val.MYI'; try to repair it

70705 14:01:37 [ERROR] Got error 127 when reading table './scalar_store/scalar_db_sessions'
170705 14:01:39 [ERROR] /usr/libexec/mysqld: Incorrect key file for table './scalar_store/scalar_db_sessions.MYI'; try to repair it
170705 14:01:44 [ERROR] /usr/libexec/mysqld: Incorrect key file for table './scalar_store/scalar_db_sessions.MYI'; try to repair it
170705 14:01:49 [ERROR] /usr/libexec/mysqld: Incorrect key file for table './scalar_store/scalar_db_sessions.MYI'; try to repair it
170705 14:01:54 [ERROR] /usr/libexec/mysqld: Incorrect key file for table './scalar_store/scalar_db_sessions.MYI'; try to repair it
170705 14:01:59 [ERROR] /usr/libexec/mysqld: Incorrect key file for table './scalar_store/scalar_db_sessions.MYI'; try to repair it
170705 14:02:04 [ERROR] /usr/libexec/mysqld: Incorrect key file for table './scalar_store/scalar_db_sessions.MYI'; try to repair it
170705 14:02:09 [ERROR] /usr/libexec/mysqld: Incorrect key file for table './scalar_store/scalar_db_sessions.MYI'; try to repair it
170705 14:02:14 [ERROR] /usr/libexec/mysqld: Incorrect key file for table './scalar_store/scalar_db_sessions.MYI'; try to repair it
170705 14:02:19 [ERROR] /usr/libexec/mysqld: Incorrect key file for table './scalar_store/scalar_db_sessions.MYI'; try to repair it
170705 14:02:24 [ERROR] /usr/libexec/mysqld: Incorrect key file for table './scalar_store/scalar_db_sessions.MYI'; try to repair it
170705 14:02:29 [ERROR] /usr/libexec/mysqld: Incorrect key file for table './scalar_store/scalar_db_sessions.MYI'; try to repair it
170705 14:02:34 [ERROR] /usr/libexec/mysqld: Incorrect key file for table './scalar_store/scalar_db_sessions.MYI'; try to repair it

**Comment by craigdietrich** [comment]
Yikes, this looks like a pretty deeply rooted issue with your webserver.  As a first step, are you sure that .htaccess is being used by your webserver?  It's needed for URL routing.  As far as the DB errors, this looks like it could be a simple problem of not having the correct values plugged in to system/application/config/database.php.

Any luck getting it going?
