### ISSUE TITLE
Security restrictions in Scalar registrations

### ISSUE THREAD

**Issue by pguerr061703** [anvc/scalar#76]
Hello,
Is there any security restrictions that can assist stopping outside users from accessing my Scalar site?
I currently have edited the user_model.php to restrict registration to just my university's @institution.edu

**Comment by craigdietrich** [comment]
Yes, see http://scalar.usc.edu/works/guide2/local-settings

I'd be careful changing Scalar system files like models as they will be overwritten if you update.

**Comment by pguerr061703** [comment]
It appears our Scalar site may have been compromised.  The security at the university is looking to see where these fake  @university.edu accounts were created.  This is a nightmare for me right now. Is there any logs to explain how these accounts got created ?  Looking in /var/www/html/scalar/system/application/logs ..but NOTHING about user account are present. 

My belief is that there is NO validation of email address. So even a random person can fake an @university account to register to scalar... .Goodness.  Please let me know any best practices for security. Can LDAP authentication work ? How so?

**Comment by craigdietrich** [comment]
Correct, there is presently no email validation in Scalar.  If you wanted to write up the module and do a pull request, that'd be awesome.

You could easily set a registration key (see my previous comment).

LDAP would work perfectly.  You'll see fields for that in local_settings.php, as well.

If you followed the INSTALL.txt correctly, you should be a "super admin" for your Scalar install, in which case when you head to the Dashboard you'll see extra tabs: All Users, All Books, and Tools.  Between thee three you can easily delete any problem (spam) books and problem user accounts.

**Comment by pguerr061703** [comment]
Can I remove the registration link from our scalar site? Can you tell me how to use ldap settings to authenticate ?  Our site has been compromised. Where are the logs?

**Comment by pguerr061703** [comment]
Can you let me know where the logs are for user creation ?  Security is looking into the logs

**Comment by craigdietrich** [comment]
Adding a registration key would block registrations.

The LDAP fields are kept in local_setting.php. The values to put there depend on how your school has set up LDAP.

If your site is compromised go to All Books, All Users, and Tools tabs in the Dashboard as a super admin and simply delete the problem books and/or users.

**Comment by pguerr061703** [comment]
Hi Can you please validate my settings below.  Will this work? Can I have "ou=<my OU>,dc=subdomain1,dc=subdomain2,dc=subdomain3,dc=EDU" on that line below ?



//My school LDAP settings 
$config['use_ldap'] = (getenv('SCALAR_USE_LDAP') ? getenv('SCALAR_USE_LDAP') : **true**);  // Default: off
$config['ldap_server'] = (getenv('SCALAR_LDAP_SERVER') ? getenv('SCALAR_LDAP_SERVER') : "**myldapderver.com**");
$config['ldap_port'] = (getenv('SCALAR_LDAP_PORT') ? getenv('SCALAR_LDAP_PORT') : **636**);
$config['ldap_basedn'] = (getenv('SCALAR_LDAP_BASEDN') ? getenv('SCALAR_LDAP_BASEDN') : "**ou=myOU,dc=domain1,dc=subdomain2,dc=subdomain3,dc=EDU**");
$config['ldap_uname_field'] = (getenv('SCALAR_LDAP_UNAME_FIELD') ? getenv('SCALAR_LDAP_UNAME_FIELD') : "**uid**");

**Comment by craigdietrich** [comment]
I literally have no idea, I've never set up LDAP. Someone else committed the LDAP upgrade to our GitHub as a pull request. But I've heard other places have used it fine so I'm confidant it works correctly.

**Comment by pguerr061703** [comment]
can i take down the "registration page" and "login page" from Scalar?
We want no users logging in at this point.

**Comment by craigdietrich** [comment]
Is suppose you could return false in both those methods in the login_model. But then you-yourself wouldn't even be able to login.

Requisite warning about adjusting system files if you plan to update Scalar.

**Comment by pguerr061703** [comment]
How does Scalar use LDAP ? Does it authenticate the user's email address? What is the field that is being looked at for LDAP authentication?

**Comment by craigdietrich** [comment]
Take a look at the login_model, the LDAP function is in there.

**Comment by pguerr061703** [comment]
Thanks. Where are the logs for user authentication access?

**Comment by craigdietrich** [comment]
You can set the log threashhold in config.php, but I don't think the logs will contain what you're looking for.

**Comment by pguerr061703** [comment]
LDAP is authenticating via email and password. Can we change this to authenticate via UID ? If so, how can we do this?

**Comment by pguerr061703** [comment]
Hi. THank you for your time helping me. I learned a great deal on Scalar.
1)User creation is not validating email addresses. correct?
2)Logs for user access. Is there a way to get that? We are looking at when some possible bogus accounts may have been created. Highly important.
3)Disable registration link on scalar page (how can i do that?)
4) Support for CAS (Central Authentication Service) available?
Appreciate any help on any of these highly critical questions on securing our Scalar site.
Thank you, again.

**Comment by craigdietrich** [comment]
> LDAP is authenticating via email and password. Can we change this to authenticate via UID ? If so, how can we do this?

I don't know enough about PHP's ldap functions that are kept in the user_model's get_from_ldap_by_email_and_password() method to know what this config item in local_settings.php is communicating:

$config['ldap_uname_field'] = (getenv('SCALAR_LDAP_UNAME_FIELD') ? getenv('SCALAR_LDAP_UNAME_FIELD') : "uid");

It seems to me that if the system as presently designed accepts email addresses than 'uid' would be referring to an email address.  Maybe changing it to something else would accept some other user field.

**Comment by craigdietrich** [comment]
> 1)User creation is not validating email addresses. correct?

Correct.  

Although, of course, LDAP does its own validation if you have that turned on.

> 2)Logs for user access. Is there a way to get that? We are looking at when some possible bogus accounts may have been created. Highly important.

Like mentioned you could increase the log threshold in config.php to see what that gets you.  Anything beyond that you'd need to insert actions that write to the log into the login methods:

log_message($level, $message);

See https://www.codeigniter.com/user_guide/general/errors.html?highlight=logs

> 3)Disable registration link on scalar page (how can i do that?)

As mentioned a few times before, adding a registration key to local_settings.php will block registrations.

Anything beyond that you'd need to rewrite the core.  For example you could add a local settings option like,

$config['hide_registration'] = [true|false};

If true then the various places that the registration link is present you could suppress it, and even block the registration page itself.

> 4) Support for CAS (Central Authentication Service) available?

No idea, never used it.  But you'd need to rewrite the core to add support similar to the LDAP setup.

In all of these cases if you implemented the code in such a way that it relied on config items and ran a pull request we'd be happy to roll them into the repo.

**Comment by pguerr061703** [comment]
Do you know the directory or name of file where I can find the landing home page for scalar.?

**Comment by craigdietrich** [comment]
system/application/modules/book_list

You can create your own module then point to it with the $config['active_book_list'] = 'book_list'; setting.

**Comment by pguerr061703** [comment]
I'm building a new Red hat Scalar server with new Scalar version 2.17a, as management has directed.  Is there a way to copy all media/books and users from my old Scalar server to my new server? If so, what directories or export/import features can I perform?  
Thanks.

**Comment by pguerr061703** [comment]
Is there a way to display php errors? I'm testing LDAP, but no errors are showing on screen, after LDAP configuration is in place.

**Comment by craigdietrich** [comment]
Change 'production' to 'development' in /codeigniter.php.

You might want to spend more time getting to know Scalar and its underlying system, a lot of these questions have well-documented answers.  https://www.codeigniter.com/user_guide/general/environments.html | http://scalar.usc.edu/works.guide2

**Comment by pguerr061703** [comment]
Here's my error 

A PHP Error was encountered

Severity: Warning

Message: ldap_start_tls(): Unable to start TLS: Can't contact LDAP server

Filename: models/user_model.php

Line Number: 182

**Comment by pguerr061703** [comment]
Can someone please show me a working ldap configuration in Scalar. Getting errors above.

**Comment by pguerr061703** [comment]
What version of codeignitor is on Scalar 2.17a ?
