### ISSUE TITLE
Import users and books from one scalar instance to another scalar instance(new version)

### ISSUE THREAD

**Issue by pguerr061703** [anvc/scalar#79]
Is there a way to import books and articles and users from one Scalar instance on one server (2.11) to another scalar instance (2.17a)? Is it as simple as copying directories or possibly performing some kind of export/import ? Please let me know as soon as possible. Thank you kindly

**Comment by craigdietrich** [comment]
There is an import/export transfer tool that is well documented in INSTALL.txt and the Scalar 2 Guide's Advanced Features section.

**Comment by pguerr061703** [comment]
Where can I find the link to the Scalar 2 guide advanced feature section ?
