### ISSUE TITLE
Getting an error logging into scalar. Can someone please help ??

### ISSUE THREAD

**Issue by pguerr061703** [anvc/scalar#80]
Fatal error: Call to a member function num_rows() on a non-object in /var/www/html/scalar/system/libraries/Session.php on line 233 

Logs are not showing anything of help:
/var/www/html/scalar/system/application/logs/
DEBUG - 2017-11-06 14:31:32 --> Session routines successfully run
DEBUG - 2017-11-06 14:31:32 --> Helper loaded: url_helper
DEBUG - 2017-11-06 14:31:32 --> Helper loaded: html_helper
DEBUG - 2017-11-06 14:31:32 --> Helper loaded: language_helper
DEBUG - 2017-11-06 14:31:32 --> Helper loaded: array_helper
DEBUG - 2017-11-06 14:31:32 --> Helper loaded: directory_helper
DEBUG - 2017-11-06 14:31:32 --> Config file loaded: /var/www/html/scalar/system/application/config/rdf.php
DEBUG - 2017-11-06 14:31:32 --> Config file loaded: /var/www/html/scalar/system/application/config/local_settings.php
DEBUG - 2017-11-06 14:31:32 --> Model Class Initialized
DEBUG - 2017-11-06 14:31:32 --> Model Class Initialized
DEBUG - 2017-11-06 14:31:32 --> Model Class Initialized
DEBUG - 2017-11-06 14:31:32 --> Language file loaded: language/en/content_lang.php
DEBUG - 2017-11-06 14:31:32 --> Model Class Initialized
DEBUG - 2017-11-06 14:31:32 --> File loaded: /var/www/html/scalar/system/application/views/modules/cover/login.php
DEBUG - 2017-11-06 14:31:32 --> File loaded: /var/www/html/scalar/system/application/views/modules/cover/index_title.php
DEBUG - 2017-11-06 14:31:32 --> File loaded: /var/www/html/scalar/system/application/views/modules/cover/index_cover.php
DEBUG - 2017-11-06 14:31:32 --> File loaded: /var/www/html/scalar/system/application/views/modules/book_list/book_list.php
DEBUG - 2017-11-06 14:31:32 --> File loaded: /var/www/html/scalar/system/application/views/arbors/admin/wrapper.php
DEBUG - 2017-11-06 14:31:32 --> Final output sent to browser
DEBUG - 2017-11-06 14:31:32 --> Total execution time: 0.0799
DEBUG - 2017-11-06 14:31:42 --> Config Class Initialized
DEBUG - 2017-11-06 14:31:42 --> Hooks Class Initialized
DEBUG - 2017-11-06 14:31:42 --> Utf8 Class Initialized
DEBUG - 2017-11-06 14:31:42 --> UTF-8 Support Enabled
DEBUG - 2017-11-06 14:31:42 --> URI Class Initialized
DEBUG - 2017-11-06 14:31:42 --> Router Class Initialized
DEBUG - 2017-11-06 14:31:42 --> No URI present. Default controller set.
DEBUG - 2017-11-06 14:31:42 --> Output Class Initialized
DEBUG - 2017-11-06 14:31:42 --> Security Class Initialized
DEBUG - 2017-11-06 14:31:42 --> Input Class Initialized
DEBUG - 2017-11-06 14:31:42 --> Global POST and COOKIE data sanitized
DEBUG - 2017-11-06 14:31:42 --> Language Class Initialized
DEBUG - 2017-11-06 14:31:42 --> Loader Class Initialized
DEBUG - 2017-11-06 14:31:42 --> Controller Class Initialized
DEBUG - 2017-11-06 14:31:42 --> Session Class Initialized
DEBUG - 2017-11-06 14:31:42 --> Helper loaded: string_helper
DEBUG - 2017-11-06 14:31:42 --> Encrypt Class Initialized
DEBUG - 2017-11-06 14:31:42 --> Database Driver Class Initialized
DEBUG - 2017-11-06 14:31:42 --> A session cookie was not found.
DEBUG - 2017-11-06 14:31:42 --> Session routines successfully run
DEBUG - 2017-11-06 14:31:42 --> Helper loaded: url_helper
DEBUG - 2017-11-06 14:31:42 --> Helper loaded: html_helper
DEBUG - 2017-11-06 14:31:42 --> Helper loaded: language_helper
DEBUG - 2017-11-06 14:31:42 --> Helper loaded: array_helper
DEBUG - 2017-11-06 14:31:42 --> Helper loaded: directory_helper
DEBUG - 2017-11-06 14:31:42 --> Config file loaded: /var/www/html/scalar/system/application/config/rdf.php
DEBUG - 2017-11-06 14:31:42 --> Config file loaded: /var/www/html/scalar/system/application/config/local_settings.php
DEBUG - 2017-11-06 14:31:42 --> Model Class Initialized
DEBUG - 2017-11-06 14:31:42 --> Model Class Initialized
DEBUG - 2017-11-06 14:31:42 --> Model Class Initialized
DEBUG - 2017-11-06 14:31:42 --> Language file loaded: language/en/content_lang.php
DEBUG - 2017-11-06 14:31:42 --> Model Class Initialized
DEBUG - 2017-11-06 14:31:42 --> File loaded: /var/www/html/scalar/system/application/views/modules/cover/login.php
DEBUG - 2017-11-06 14:31:42 --> File loaded: /var/www/html/scalar/system/application/views/modules/cover/index_title.php
DEBUG - 2017-11-06 14:31:42 --> File loaded: /var/www/html/scalar/system/application/views/modules/cover/index_cover.php
DEBUG - 2017-11-06 14:31:42 --> File loaded: /var/www/html/scalar/system/application/views/modules/book_list/book_list.php
DEBUG - 2017-11-06 14:31:42 --> File loaded: /var/www/html/scalar/system/application/views/arbors/admin/wrapper.php
DEBUG - 2017-11-06 14:31:42 --> Final output sent to browser
DEBUG - 2017-11-06 14:31:42 --> Total execution time: 0.0801
DEBUG - 2017-11-06 14:31:52 --> Config Class Initialized
DEBUG - 2017-11-06 14:31:52 --> Hooks Class Initialized
DEBUG - 2017-11-06 14:31:52 --> Utf8 Class Initialized
DEBUG - 2017-11-06 14:31:52 --> UTF-8 Support Enabled
DEBUG - 2017-11-06 14:31:52 --> URI Class Initialized
DEBUG - 2017-11-06 14:31:52 --> Router Class Initialized
DEBUG - 2017-11-06 14:31:52 --> No URI present. Default controller set.
DEBUG - 2017-11-06 14:31:52 --> Output Class Initialized
DEBUG - 2017-11-06 14:31:52 --> Security Class Initialized
DEBUG - 2017-11-06 14:31:52 --> Input Class Initialized
DEBUG - 2017-11-06 14:31:52 --> Global POST and COOKIE data sanitized
DEBUG - 2017-11-06 14:31:52 --> Language Class Initialized
DEBUG - 2017-11-06 14:31:52 --> Loader Class Initialized
DEBUG - 2017-11-06 14:31:52 --> Controller Class Initialized
DEBUG - 2017-11-06 14:31:52 --> Session Class Initialized
DEBUG - 2017-11-06 14:31:52 --> Helper loaded: string_helper
DEBUG - 2017-11-06 14:31:52 --> Encrypt Class Initialized
DEBUG - 2017-11-06 14:31:52 --> Database Driver Class Initialized
DEBUG - 2017-11-06 14:31:52 --> A session cookie was not found.
DEBUG - 2017-11-06 14:31:52 --> Session routines successfully run
DEBUG - 2017-11-06 14:31:52 --> Helper loaded: url_helper
DEBUG - 2017-11-06 14:31:52 --> Helper loaded: html_helper
DEBUG - 2017-11-06 14:31:52 --> Helper loaded: language_helper
DEBUG - 2017-11-06 14:31:52 --> Helper loaded: array_helper
DEBUG - 2017-11-06 14:31:52 --> Helper loaded: directory_helper
DEBUG - 2017-11-06 14:31:52 --> Config file loaded: /var/www/html/scalar/system/application/config/rdf.php
DEBUG - 2017-11-06 14:31:52 --> Config file loaded: /var/www/html/scalar/system/application/config/local_settings.php
DEBUG - 2017-11-06 14:31:52 --> Model Class Initialized
DEBUG - 2017-11-06 14:31:52 --> Model Class Initialized
DEBUG - 2017-11-06 14:31:52 --> Model Class Initialized
DEBUG - 2017-11-06 14:31:52 --> Language file loaded: language/en/content_lang.php
DEBUG - 2017-11-06 14:31:52 --> Model Class Initialized
DEBUG - 2017-11-06 14:31:52 --> File loaded: /var/www/html/scalar/system/application/views/modules/cover/login.php
DEBUG - 2017-11-06 14:31:52 --> File loaded: /var/www/html/scalar/system/application/views/modules/cover/index_title.php
DEBUG - 2017-11-06 14:31:52 --> File loaded: /var/www/html/scalar/system/application/views/modules/cover/index_cover.php
DEBUG - 2017-11-06 14:31:52 --> File loaded: /var/www/html/scalar/system/application/views/modules/book_list/book_list.php
DEBUG - 2017-11-06 14:31:52 --> File loaded: /var/www/html/scalar/system/application/views/arbors/admin/wrapper.php
DEBUG - 2017-11-06 14:31:52 --> Final output sent to browser
DEBUG - 2017-11-06 14:31:52 --> Total execution time: 0.0579

**Comment by tmoon8730** [comment]
I am seeing this same error but am also stumped on how to fix it. I am also seeing this error but I am not sure if they are connected:

``` Severity: Warning
Message: mysqli_real_escape_string() expects parameter 1 to be mysqli, boolean given
Filename: mysqli/mysqli_driver.php
Line Number: 316 
```


If anybody has any idea how to fix this that would be greatly appreciated.

**Comment by tmoon8730** [comment]
I am running this project in a Docker container and forgot to import the sql dump file during installation. 

If you see this type of error try importing the dump file as specified in the install.txt document. It worked for me.

**Comment by craigdietrich** [comment]
Great to hear!  Thanks for the input.
