### ISSUE TITLE
Add German Translation

### ISSUE THREAD

**Issue by mogoh** [anvc/scalar#83]
Hello,

I would like to add German translation to scalar, especially for the frontend. This could be the issue to track progress.

There is this directory `/system/language/english/` which I guess should be copied and andjusted. Are there more php-strings not in there?

Also some strings to translate are spread over some javascript/jquery files. As I am not a javascript developer I don't know how to prepere translation. Do you use some tool/framework for internationalization?

I think I can provide all German translation (no promises) but I don't think I can do all necessary preparation. Can someone prepare i18n, so I can do l10n?

**Comment by mogoh** [comment]
As our project now will be english-only, this issue can be closed.

**Comment by craigdietrich** [comment]
Just to follow up with your question: our language file kept in that folder is very neglected.  The long term strategy for internationalizing the system texts would first include getting all of the system texts into the english file, then duplicating that into various languages.
