### ISSUE TITLE
Unexpected Behavior of Map Widget

### ISSUE THREAD

**Issue by JoelleByars** [anvc/scalar#86]
Expected Behavior:
Map widget was expected to be in the righthand margin.
Inline map widget expected aligned with text wrap.

Observed Behavior:
Map widget did not appear in the right-hand margin, appeared inside margin and altered text formatting.
Inline map widget appeared inline but altered text formatting.

Please cc @rcrath

**Comment by craigdietrich** [comment]
Could you post a screengrab?

**Comment by rcrath** [comment]
here is the (hand adjusted) html:
``` 
 <br /><a data-widget="map" data-nodes="barclay-st" data-size="small" data-align="right" data-caption="description" class="inlineWidget inline" name="scalar-inline-widget"></a>
</p>
```
for this: 
![screenshot from 2018-03-17 10-43-11](https://user-images.githubusercontent.com/944636/37559810-481a308e-29d0-11e8-80d5-a0b05b425de8.png)

**Comment by rcrath** [comment]
Inline is looking correct today:
![screenshot from 2018-03-17 10-47-10](https://user-images.githubusercontent.com/944636/37559831-cb5ff1cc-29d0-11e8-9348-a0a9e3da7eeb.png)
![screenshot from 2018-03-17 10-47-56](https://user-images.githubusercontent.com/944636/37559833-cef2f49c-29d0-11e8-9dd0-b2ba8e075239.png)

... and the linked widget appears to be fine today.  Maybe we just had something weird in cache on that computer as this is on a different one.  
![screenshot from 2018-03-17 10-50-35](https://user-images.githubusercontent.com/944636/37559862-52de4658-29d1-11e8-9ac9-d0abdba9ea27.png)

![screenshot from 2018-03-17 10-51-37](https://user-images.githubusercontent.com/944636/37559864-57e04a2a-29d1-11e8-9fe6-768e1387f7be.png)


Thanks for fixing it! ;) plz close.

**Comment by rcrath** [comment]
Today it is working fine on another computer.  Maybe we needed to clear browser cache or something. Thanks for the magic fix!

inline:
![screenshot from 2018-03-17 10-50-35](https://user-images.githubusercontent.com/944636/37559949-195c2b14-29d3-11e8-9845-b7d478a0b6f6.png)
![screenshot from 2018-03-17 10-51-37](https://user-images.githubusercontent.com/944636/37559950-1c9655ca-29d3-11e8-9933-f369364e83e7.png)

**Comment by rcrath** [comment]
I do have a question about map zoom, but I'll make a separate issue.

**Comment by craigdietrich** [comment]
From the looks of the text you might have gobbledegook resulting from copy-pasting from something like MS-Word... this would result in problems with the page rendering correctly.

I’d suggest looking at the page content in “Source” view... if this is indeed the case you’ll want to re-cut-and-late into the Source view, or, use the “page from word” button in the WYSIWYG editor.

**Comment by rcrath** [comment]
Ok. It was from word. @JoelleByars this is a good reason to use the paste from word function. Ok to close as it works no.
