### ISSUE TITLE
Defiant behavior in Scalar 2's "pageLoadComplete" event

### ISSUE THREAD

**Issue by damg70** [anvc/scalar#88]
We (david goldberg and @rcrath) are trying to apply styles to the ordered list within the div "#mainMenuInside" in the upper left navigation menu.

In particular we are trying to remove the numbering of the ordered list ([https://github.com/digiah/sobf/issues/25](https://github.com/digiah/sobf/issues/25)) and have tried using the standard CSS: **list-style-type: none** in the "global" CSS settings and the page-specific custom style tab. This does not work in any case that we have attempted via CSS. 

So we followed instructions for using "pageLoadComplete," and tried the following via the "book properties" tab in the dashboard:

**$(document).ready(function() {
  $('body').bind('pageLoadComplete',function() {
    $('#mainMenuInside li.body ol').css('background-color', "#F00");
    $('#mainMenuInside li.body ol').css('list-type-style', "none");
  });
});**

The first CSS assignment for the background color is successful: the bgcolor of the &lt;ol&gt; becomes red, but the attempt to set the list-style-type to none does not work. 

Using browser inspection tools we have verified that the page load order is correct. We see jquery call inserted above others that we have in place on individual pages, but the second css instruction is ignored.

In the screen captures below you can see that the styling for the background color and the list style have been applied, but only the former has actually "stuck."

<img width="506" alt="scalar dom" src="https://user-images.githubusercontent.com/6117953/37686319-04efc8c4-2c3b-11e8-9844-77b1791e6004.png">

Here is a screen shot of how the event handler shows up in the script tag... we're sure if "on" or "bind" makes a difference, but have tried both.

<img width="486" alt="scalar script" src="https://user-images.githubusercontent.com/6117953/37686314-0052b02e-2c3b-11e8-9055-98e42acada66.png">

here is a screen shot of the menu in its visible state.

<img width="390" alt="scalar dropdown" src="https://user-images.githubusercontent.com/6117953/37686409-64f90550-2c3b-11e8-85cc-4ba5de13985d.png">

Thanks for looking at this issue! Since having the numbers on the list and the roman numerals that are used in the titles of the actual chapters are out of sync this is a priority UI issue for us. Any help would be appreciated.

**Comment by eloyer** [comment]
Yes, as you discovered, the numbering in the menu isn't accomplished through typical means. This style should take care of it:

`.navbar li.mainMenu>.mainMenuDropdown>#mainMenuInside>li>ol>li>a:first-child:before { content: none; }`

Let us know if that doesn't work!

**Comment by rcrath** [comment]
@eloyer thanks, it worked like a charm.  plz close!
