### ISSUE TITLE
use <p> tag and not <br> on return

### ISSUE THREAD

**Issue by jgmac1106** [anvc/scalar#94]
When typing in the tinyMCE rich text editor I find the return carriage translates into a line break rather than opening and closing a new paragraph.

Just doesn't sit well with me semantically. Is there any place I can change?

**Comment by craigdietrich** [comment]
Scalar adds <p> tags around each paragraph, anyways, in the front-end.  This is so we can position any embedded media alongside the paragraphs in the text.
