### ISSUE TITLE
Scalar - soundclound 

### ISSUE THREAD

**Issue by pguerr061703** [anvc/scalar#96]
I've been testing Scalar on a RedHat virtual server and found the following issues:
When trying to search SoundCloud, I get a message,

From: <my sitename.domainname>
Missing API key for this archive. Please contact an administrator to add a key to the local settings.

Any idea how to fix this? Not sure what API key is being referred or how to add it.
Thank you

**Comment by craigdietrich** [comment]
All API keys are kept in local_settings.php:

http://scalar.usc.edu/works/guide2/local-settings
