### ISSUE TITLE
Scalar - search results do not show any results

### ISSUE THREAD

**Issue by pguerr061703** [anvc/scalar#97]
When I use Scalar to search for youtube videos,  (in this example I searched for 'man', you fail to get any results.) . See attached pic.  Is there something wrong with the search mechanism?

Thank you.

![screen shot 2018-08-14 at 11 42 20 am 1](https://user-images.githubusercontent.com/12171475/44104385-bad01de8-9fbc-11e8-95e5-a81238ac23ff.jpg)

**Comment by craigdietrich** [comment]
All API keys are kept in local_settings.php:  http://scalar.usc.edu/works/guide2/local-settings

However, if you're using an older version of Scalar there won't be a YouTube API key ... that is a more recent addition after Google changed the requirements.  While updating Scalar make sure to take a look at: https://github.com/anvc/scalar/wiki/Changes-to-config-files-over-time , you'll see the YouTube API key listed there.
